---
title: Comment pouvons-nous vous aider ?
choices:
- label: ğŸ’ğŸ»â€â™€ï¸ J'ai une question
  id: help
  link:
    title: Votre question porte sur ?
    choices:
    - label: "Des donnÃ©es en particulier"
      id: dataset
      link:
        title: Sur quelles donnÃ©es avez vous des questions ?
        choices:
          - label: "RNA"
            id: rna
            link:
              path : answers/numero_rna.md
          - label: "Personnes dÃ©cÃ©dÃ©es"
            id: deces
            link:
              path : answers/deces.md
          - label: "Formation"
            id: formation
            link:
              path : answers/formation.md
          - label: "SIREN & SIRET"
            id: siret
            link:
              path : answers/siret.md
          - label: "DVF"
            id: dvf
            link:
              path : answers/dvf.md
          - label: "Base Adresse Nationale (BAN)"
            id: ban
            link:
              path : answers/ban.md
          - label: "API dÃ©coupage administratif"
            id: decoupage
            link:
              path : answers/decoupe.md
          - label: "IRVE"
            id: irve
            link:
              path : answers/irve.md
          - label: "Autre"
            id: other
            link:
              path : answers/question_donnees.md
    - label: "Un procÃ©dure administrative"
      id: admin
      link:
        path : answers/demarches_admin.md
    - label: "L'utilisation de data.gouv.fr"
      id: datagouv
      link:
        form:
          title: Nous vous invitons Ã  consulter nos guides avant de nous Ã©crire
          recipient: support@data.gouv.fr
    - label: "L'ouverture des donnÃ©es"
      id: open
      link:
        form:
          title: De quelles donnÃ©es revez-vous ?
          recipient: support@data.gouv.fr
- label: ğŸ’¡ Demande de fonctionnalitÃ©
  id: feature
  link:
    form:
      title: De quelle fonctionnalitÃ© revez-vous ?
      recipient: support@data.gouv.fr
- label: ğŸ› Soumettre un bug 
  id: bug
  link:
    form:
      title: Quel problÃ¨me rencontrez-vous ?
      recipient: support@data.gouv.fr
- label: ğŸ’¬ Faire un retour sur data.gouv.fr
  id: feedback
  link:
    form:
      title: Que souhaitez-vous nous dire ?
      recipient: support@data.gouv.fr