---
title: Qui êtes-vous ?
choices:
- label: Un particulier
  id: particulier
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "J'ai une question sur une procédure administrative"
      id: procedure-administrative
      link:
        path: answers/demarches_admin.md
    - label: "J'ai constaté une erreur ou j'ai une question relative à un jeu de donnée publié sur data.gouv.fr"
      id: jeu-de-donnee
      link:
        path: answers/question_donnees.md
    - label: "J'ai un problème technique dans l'utilisation de la plateforme data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Je souhaite signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "J'ai une demande relative à l'ouverture des données publiques : données absentes ou difficiles à trouver"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    #- label: "J'ai une question relative à des données à caractère personnel"
      #link:
        #title: 'Votre question concerne :'
        #choices:
        #- label: La base de données des demandes de valeurs foncières (transactions immobilières)
          #link:
            #content: La réponse est non
        #- label: Le Repertoire national des associations (RNA)
          #link:
            #content: La réponse est toujours non 
        #- label: La base Sirene des entreprises et de leurs établissements (SIREN, SIRET)
          #link:
            #content: "Puisqu'on vous dit que c'est non"
        #- label: Le fichier des personnes décédées
          #link:
            #content: Bon très bien, les réponses à ces questions sont
        #- label: Autre
          #link:
            #form:
              #title: Contactez-nous
              #recipient: ouverture@data.gouv.fr
- label: Une ou un journaliste
  id: journaliste
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "J'ai constaté une erreur ou j'ai une question relative à un jeu de donnée publié sur data.gouv.fr"
      id: jeu-de-donnee
      link:
        path: answers/question_donnees.md
    - label: "J'ai un problème technique dans l'utilisation de la plateforme data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Je souhaite signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "J'ai une demande relative à l'ouverture des données publiques : données absentes ou difficiles à trouver"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
- label: Une chercheuse ou un chercheur 
  id: chercheur
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "J'ai constaté une erreur ou j'ai une question relative à un jeu de donnée publié sur data.gouv.fr"
      id: jeu-de-donnee
      link:
        path: answers/question_donnees.md
    - label: "J'ai un problème technique dans l'utilisation de la plateforme data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Je souhaite signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "J'ai une demande relative à l'ouverture des données publiques : données absentes ou difficiles à trouver"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    #- label: "J'ai une question relative à des données à caractère personnel"
      #link:
        #title: 'Votre question concerne :'
        #choices:
        #- label: La base de données des demandes de valeurs foncières (transactions immobilières)
          #link:
            #content: La réponse est non
        #- label: Le Repertoire national des associations (RNA)
          #link:
            #content: La réponse est toujours non 
        #- label: La base Sirene des entreprises et de leurs établissements (SIREN, SIRET)
          #link:
            #content: "Puisqu'on vous dit que c'est non"
        #- label: Le fichier des personnes décédées
          #link:
            #content: Bon très bien, les réponses à ces questions sont
        #- label: Autre
          #link:
            #form:
              #title: Contactez-nous
              #recipient: ouverture@data.gouv.fr
- label: Une administration centrale
  id: administration-centrale
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "J'ai constaté une erreur ou j'ai une question relative à un jeu de donnée publié sur data.gouv.fr"
      id: jeu-de-donnee
      link:
        path: answers/question_donnees.md
    - label: "Je souhaite référencer mes données sur data.gouv.fr"
      id: referencement
      link:
        title: 'Où sont situées vos données ?'
        choices:
        - label: Mes données sont sur un portail open data existant
          id: moissonnage
          link:
            form:
              title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
              recipient: moissonnage@data.gouv.fr
        - label: Mes données ne sont pas sur un portail open data existant
          id: ouverture
          link:
            form:
              title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
              recipient: ouverture@data.gouv.fr
    - label: "J'ai un problème technique dans l'utilisation de la plateforme data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Je souhaite signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "J'ai une demande relative à l'ouverture des données publiques : données absentes ou difficiles à trouver"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Je souhaite faire une demande d'homologation de licence"
      id: licence
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: homologation.licence@data.gouv.fr
    - label: "Je souhaite faire certifier mon organisation sur data.gouv.fr"
      id: certification
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: certification@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    #- label: "J'ai une question relative à des données à caractère personnel"
      #link:
        #title: 'Votre question concerne :'
        #choices:
        #- label: La base de données des demandes de valeurs foncières (transactions immobilières)
          #link:
            #content: La réponse est non
        #- label: Le Repertoire national des associations (RNA)
          #link:
            #content: La réponse est toujours non 
        #- label: La base Sirene des entreprises et de leurs établissements (SIREN, SIRET)
          #link:
            #content: "Puisqu'on vous dit que c'est non"
        #- label: Le fichier des personnes décédées
          #link:
            #content: Bon très bien, les réponses à ces questions sont
        #- label: Autre
          #link:
            #form:
              #title: Contactez-nous
              #recipient: ouverture@data.gouv.fr
- label: Une collectivité territoriale
  id: collectivite-territoriale
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "J'ai constaté une erreur ou j'ai une question relative à un jeu de donnée publié sur data.gouv.fr"
      id: jeu-de-donnee
      link:
        path: answers/question_donnees.md
    - label: "J'ai un problème technique dans l'utilisation de la plateforme data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Je souhaite signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "J'ai une demande relative à l'ouverture des données publiques : données absentes ou difficiles à trouver"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
     - label: "Je souhaite référencer mes données sur data.gouv.fr"
      id: referencement
      link:
        title: 'Où sont situées vos données ?'
        choices:
        - label: Mes données sont sur un portail open data existant
          id: moissonnage
          link:
            form:
              title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
              recipient: moissonnage@data.gouv.fr
        - label: Mes données ne sont pas sur un portail open data existant
          id: ouverture
          link:
            form:
              title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
              recipient: ouverture@data.gouv.fr
    - label: "Je souhaite faire une demande d'homologation de licence"
      id: licence
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: homologation.licence@data.gouv.fr
    - label: "Je souhaite faire certifier mon organisation sur data.gouv.fr"
      id: certification
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: certification@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    #- label: "J'ai une question relative à des données à caractère personnel"
      #link:
        #title: 'Votre question concerne :'
        #choices:
        #- label: La base de données des demandes de valeurs foncières (transactions immobilières)
          #link:
            #content: La réponse est non
        #- label: Le Repertoire national des associations (RNA)
          #link:
            #content: La réponse est toujours non 
        #- label: La base Sirene des entreprises et de leurs établissements (SIREN, SIRET)
          #link:
            #content: "Puisqu'on vous dit que c'est non"
        #- label: Le fichier des personnes décédées
          #link:
            #content: Bon très bien, les réponses à ces questions sont
        #- label: Autre
          #link:
            #form:
              #title: Contactez-nous
              #recipient: ouverture@data.gouv.fr
- label: Une entreprise
  id: entreprise
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "J'ai constaté une erreur ou j'ai une question relative à un jeu de donnée publié sur data.gouv.fr"
      id: jeu-de-donnee
      link:
        path: answers/question_donnees.md
    - label: "J'ai un problème technique dans l'utilisation de la plateforme data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Je souhaite signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "J'ai une demande relative à l'ouverture des données publiques : données absentes ou difficiles à trouver"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    #- label: "J'ai une question relative à des données à caractère personnel"
      #link:
        #title: 'Votre question concerne :'
        #choices:
        #- label: La base de données des demandes de valeurs foncières (transactions immobilières)
          #link:
            #content: La réponse est non
        #- label: Le Repertoire national des associations (RNA)
          #link:
            #content: La réponse est toujours non 
        #- label: La base Sirene des entreprises et de leurs établissements (SIREN, SIRET)
          #link:
            #content: "Puisqu'on vous dit que c'est non"
        #- label: Le fichier des personnes décédées
          #link:
            #content: Bon très bien, les réponses à ces questions sont
        #- label: Autre
          #link:
            #form:
              #title: Contactez-nous
              #recipient: ouverture@data.gouv.fr
- label: Une association
  id: association
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "J'ai une question sur une procédure administrative"
      id: procedure-administrative
      link:
        path: answers/demarches_admin.md
    - label: "J'ai constaté une erreur ou j'ai une question relative à un jeu de donnée publié sur data.gouv.fr"
      id: jeu-de-donnee
      link:
        path: answers/question_donnees.md
    - label: "J'ai un problème technique dans l'utilisation de la plateforme data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Je souhaite signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "J'ai une demande relative à l'ouverture des données publiques : données absentes ou difficiles à trouver"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    #- label: "J'ai une question relative à des données à caractère personnel"
      #link:
        #title: 'Votre question concerne :'
        #choices:
        #- label: La base de données des demandes de valeurs foncières (transactions immobilières)
          #link:
            #content: La réponse est non
        #- label: Le Repertoire national des associations (RNA)
          #link:
            #content: La réponse est toujours non 
        #- label: La base Sirene des entreprises et de leurs établissements (SIREN, SIRET)
          #link:
            #content: "Puisqu'on vous dit que c'est non"
        #- label: Le fichier des personnes décédées
          #link:
            #content: Bon très bien, les réponses à ces questions sont
        #- label: Autre
          #link:
            #form:
              #title: Contactez-nous
              #recipient: ouverture@data.gouv.fr
- label: Autre
  id: autre
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "J'ai une question sur une procédure administrative"
      id: procedure-administrative
      link:
        path: answers/demarches_admin.md
    - label: "J'ai constaté une erreur ou j'ai une question relative à un jeu de donnée publié sur data.gouv.fr"
      id: jeu-de-donnee
      link:
        path: answers/question_donnees.md
    - label: "J'ai un problème technique dans l'utilisation de la plateforme data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Je souhaite signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "J'ai une demande relative à l'ouverture des données publiques : données absentes ou difficiles à trouver"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    #- label: "J'ai une question relative à des données à caractère personnel"
      #link:
        #title: 'Votre question concerne :'
        #choices:
        #- label: La base de données des demandes de valeurs foncières (transactions immobilières)
          #link:
            #content: La réponse est non
        #- label: Le Repertoire national des associations (RNA)
          #link:
            #content: La réponse est toujours non 
        #- label: La base Sirene des entreprises et de leurs établissements (SIREN, SIRET)
          #link:
            #content: "Puisqu'on vous dit que c'est non"
        #- label: Le fichier des personnes décédées
          #link:
            #content: Bon très bien, les réponses à ces questions sont
        #- label: Autre
          #link:
            #form:
              #title: Contactez-nous
              #recipient: ouverture@data.gouv.fr
