---
title: Qui êtes-vous ?
choices:
- label: Un testeur de cet outil de support
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: Je veux tester le formulaire de contact
      link:
        form:
          title: Contactez-nous
          recipient: test@data.gouv.fr
    - label: Je veux tester le formulaire de contact quand Zammad ne marche pas
      link:
        form:
          title: Contactez-nous (mais ça ne va pas marcher haha)
          recipient: croute@data.gouv.fr
    - label: Je veux tester une sous-question
      link:
        title: 'Vous voulez tester :'
        choices:
        - label: Du contenu en markdown
          link:
            path: answers/contenu.md
        - label: Du contenu brut
          link:
            content: Le contenu brut se configure directement dans le fichier config/question-tree.yaml
